### ISSUE TITLE
 wifi.getNetworks crash under node 0.12.7

### ISSUE THREAD

**Issue by jlucidar** [Doodle3D/connman-simplified#13]
I ran your plugin with the examples from GitHub, and the wifi.getNetworks function crashed the program : here is the message : 

```
#
# Fatal error in ../deps/v8/src/lookup.cc, line 47
# CHECK(!root->IsNull()) failed
#
==== C stack trace ===============================
(empty)
Illegal instruction (core dumped)
```

This is apparently more a problem with nodev0.12.7 than with connman or your plugin, but that's quite embarrassing...

I found a way to fix the problem for my own application in the connman-api package. you can check it there : https://github.com/jlucidar/connman-api/commit/579c408abee90161606bc9abf4e28ae9225750c3

**Comment by peteruithoven** [comment]
A fatal error, that's rude of Node.js. Thanks for finding it, we've used this library in a project, but never came across this. 
I don't really understand what's happening in your [change](https://github.com/jlucidar/connman-api/commit/579c408abee90161606bc9abf4e28ae9225750c3) though. In one case you re-enable the callback on error and finish (which you probably removed earlier). In the other you call callback after a nexttick, which seems very random...

**Comment by pcarranzav** [comment]
I think this should be fixed in [this connman-api PR](https://github.com/Doodle3D/connman-api/pull/7).

**Comment by jlucidar** [comment]
Yes, version 0.1.2 solved it, Thank you all !
